Feature branch
SufianShihab/Hello-Microverse pull request #2
Opened 2023-05-30 21:06 UTC by SufianShihab

2023-05-30 21:49 UTC, Efiamotu-1 reviewed
Hi @Rdzaman20000  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif) 
You have submitted a project, that is failing the linters check. It is important that linters are passing. please ensure linters pass before requesting for a new review
- follow the steps outlined in this [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to set up linters correctly
- [ ] Also you submitted this project in the wrong review link, please when resubmitting this project you should submit it for `hello microverse` not `finish mobile version` review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-30 22:05 UTC, levy002 requested changes
## Hello  @SufianShihab     , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlinters
- Correct git-flow :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly make sure to update your PR title and PR description by proving a well-detailed summary and title which makes your PR clean and professional and even self-explanatory. :wink: 

   - Example of good PR Summary
![image](https://user-images.githubusercontent.com/87197412/184990532-da778ab4-c789-4136-90a9-629eedd969da.png)

  ### HOW TO EDIT PR DESCRIPTION
   ![chrome-capture-2023-3-27](https://user-images.githubusercontent.com/87197412/234717222-919ba9d0-1ef1-4702-b386-4dbaf18deb08.gif)

 - Example of a good PR title
    _**Hello Microverse Project Setup**_

   ### HOW TO EDIT PR TITLE
    ![chrome-capture-2023-3-27 (1)](https://user-images.githubusercontent.com/87197412/234717588-992cb1ef-8a21-4987-ac09-5c833bfabc41.gif)


- [ ] Kindly make sure to correct all Linter errors.
 
- [ ] Kindly make sure to use the [Microverse README template](https://github.com/microverseinc/readme-template) which will help to explain your repository contents and have a clean and professional Readme. Please make sure to customize it according to your project and fill in the needed information and remember all main sections must be included except the FAQ section which is optional.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 22:48 UTC, SufianShihab commented
Hello @levy002,
I have tried to fix the issue of git-flow to my maximum limit but failed. Please tell me how can I fix that?

2023-05-30 23:18 UTC, OyePriscilla reviewed
Hi @SufianShihab 👍, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not correspond with the appropriate milestone (Hello microverse). Kindly ensure that you submitted this PR correctly on your dashboard. ℹ️ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-31 20:00 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @SufianShihab  👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)
## Highlight 
✔ Used correct GitFlow👍 
✔ No Linter Errors 👍 
✔ Professional PR👍 

## Required Changes ♻️

- [ ]  Check the comments below 

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 20:13 UTC, SufianShihab commented on README.md
> +
Hi @TuyishimireEric,
Thank you very much for your kind review. I have added the license file. Please check.

2023-05-31 20:26 UTC, Ofarouq310 approved these changes
Hi @SufianShihab, ✋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://github.com/SufianShihab/Hello-Microverse/assets/102612396/c6a2dd50-2233-4637-af70-c8c8df63b924)

## Highlights
✅ Followed GitHub workflow.
✅ Descriptive PR title and summary.
✅ No linters errors.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 20:26 UTC, Ofarouq310 commented on README.md
> +
[OPTIONAL]
- [ ] Kindly remove the Microverse logo as it was just for the template, you can add yours in case you have one or willing to have one in the future.

2023-05-31 20:26 UTC, Ofarouq310 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
[OPTIONAL]
- [ ] Kindly remove the `Live Demo` section in case you do not have its deployment link yet, once you have it add the section again. This is better for the sake of organization and setting up a professional README file.

2023-05-31 20:33 UTC, merged